
name: the-progressive-web
version: '0.1'
summary: A PWA featuring fresh content about PWA's from the YouTube API
description: |
  This is your one stop shop for learning about Progressive Web Apps. It's a
  refined search query that is fetched with a service worker using the fetch
  api, then returned to the client and updated without the need for any user
  action.

grade: stable
confinement: strict


apps:
  node-service:
    command: npm run serve
    daemon: simple
    restart-condition: always
    plugs: [network-bind]


parts:
  webserver:
    source: .
    plugin: nodejs
