
name: Chrome-Developer-Channel # you probably want to 'snapcraft register <name>'
version: '0.1'
summary: A PWA featuring fresh content about PWA's from the YouTube API
description: |
  This is your one stop shop for learning about Progressive Web Apps. It's a 
  refined search query that is fetched with a service worker using the fetch
  api, then returned to the client and updated without the need for any user
  action.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

# parts:
#  my-part:
    # See 'snapcraft plugins'
    
apps:
  docker:
    command: docker build .
    daemon: simple
    restart-condition: always
    plugs: [network-bind]
      
plugs:
    browser-sandbox:
      interface: browser-support
      allow-sandbox: false
    platform:
      interface: content
      content: ubuntu-app-platform1
      target: ubuntu-app-platform
      default-provider: ubuntu-app-platform

parts:
  webapp-container:
    source: .
    plugin: dump
    stage-packages: [ubuntu-html5-ui-toolkit]
    organize:
      'usr/share/ubuntu-html5-ui-toolkit/': www/ubuntu-html5-ui-toolkit
    prime:
      - usr/*
      - www/*
    after: [webapp-helper, desktop-ubuntu-app-platform]
